

project_id = "inudoymofztrvxhrlrek"

[functions.setup-test-environment]
verify_jwt = false

[functions.email-report-reviewed]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.password-reset-email]
verify_jwt = false

