

project_id = "inudoymofztrvxhrlrek"

[functions.create-admin-user]
verify_jwt = true

[functions.setup-test-environment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.password-reset-email]
verify_jwt = false

