
project_id = "inudoymofztrvxhrlrek"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://inudoymofztrvxhrlrek.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[functions.create-admin-user]
verify_jwt = true

[functions.setup-test-environment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.password-reset-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.generate-report-pdf]
verify_jwt = true

[edge_runtime]
enabled = true
port = 54325

